/** @type {import('tailwindcss').Config} */
module.exports = {
    content: [
        './src/**/*.{js,ts,jsx,tsx,mdx}',
    ],
    theme: {
        extend: {
            colors: {
                // Legacy CSS-var based (used by interior pages)
                'base': 'var(--bg-base)',
                'surface': 'var(--bg-surface)',
                'raised': 'var(--bg-raised)',
                'border-color': 'var(--border)',
                'blue-primary': 'var(--blue-primary)',
                'blue-accent': 'var(--blue-accent)',
                'text-primary': 'var(--text-primary)',
                'text-secondary': 'var(--text-secondary)',
                'success': 'var(--success)',
                'warning': 'var(--warning)',
                'error': 'var(--error)',
                // MD3 Design System
                'primary': '#b8c4ff',
                'primary-container': '#1e40af',
                'primary-fixed': '#dde1ff',
                'primary-fixed-dim': '#b8c4ff',
                'on-primary': '#002584',
                'on-primary-container': '#a8b8ff',
                'on-primary-fixed': '#001453',
                'on-primary-fixed-variant': '#173bab',
                'secondary': '#adc6ff',
                'secondary-container': '#0566d9',
                'secondary-fixed': '#d8e2ff',
                'secondary-fixed-dim': '#adc6ff',
                'on-secondary': '#002e6a',
                'on-secondary-container': '#e6ecff',
                'on-secondary-fixed': '#001a42',
                'on-secondary-fixed-variant': '#004395',
                'tertiary': '#bdc2ff',
                'tertiary-container': '#343fa7',
                'tertiary-fixed': '#e0e0ff',
                'tertiary-fixed-dim': '#bdc2ff',
                'on-tertiary': '#131e8c',
                'on-tertiary-container': '#b0b6ff',
                'on-tertiary-fixed': '#000767',
                'on-tertiary-fixed-variant': '#2f3aa3',
                'surface-dim': '#0e131e',
                'surface-bright': '#343946',
                'surface-container': '#1b1f2b',
                'surface-container-low': '#161b27',
                'surface-container-high': '#252a36',
                'surface-container-highest': '#303541',
                'surface-container-lowest': '#090e19',
                'surface-variant': '#303541',
                'surface-tint': '#b8c4ff',
                'on-surface': '#dee2f2',
                'on-surface-variant': '#c4c5d5',
                'outline': '#8e909f',
                'outline-variant': '#444653',
                'background': '#0e131e',
                'on-background': '#dee2f2',
                'inverse-surface': '#dee2f2',
                'inverse-on-surface': '#2b303d',
                'inverse-primary': '#3755c3',
                'md3-error': '#ffb4ab',
                'error-container': '#93000a',
                'on-error': '#690005',
                'on-error-container': '#ffdad6',
            },
            fontFamily: {
                sans: ['Inter', 'system-ui', '-apple-system', 'sans-serif'],
            },
            animation: {
                'fade-in': 'fadeIn 0.2s ease-out',
                'slide-up': 'slideUp 0.2s ease-out',
            },
            keyframes: {
                fadeIn: {
                    '0%': { opacity: '0' },
                    '100%': { opacity: '1' },
                },
                slideUp: {
                    '0%': { opacity: '0', transform: 'translateY(8px)' },
                    '100%': { opacity: '1', transform: 'translateY(0)' },
                },
            },
        },
    },
    plugins: [],
}
